// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC5KopJ0p2AL_dG8H5ZbZn2y2Lz_I0V_0',
    appId: '1:339419575615:web:b0b358c65daa3fa98f8f8a',
    messagingSenderId: '339419575615',
    projectId: 'spotify-music-api-player',
    authDomain: 'spotify-music-api-player.firebaseapp.com',
    storageBucket: 'spotify-music-api-player.appspot.com',
    measurementId: 'G-NL6RKQ2BY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX2qvEbTYwX2ygUkOoO-Rwg4p1Dm66_Ao',
    appId: '1:339419575615:android:24910d58b414f6428f8f8a',
    messagingSenderId: '339419575615',
    projectId: 'spotify-music-api-player',
    storageBucket: 'spotify-music-api-player.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQe_QKcL2mBHxyGLkgHN7m62oCRY8rt6o',
    appId: '1:339419575615:ios:657d0e31727b40c08f8f8a',
    messagingSenderId: '339419575615',
    projectId: 'spotify-music-api-player',
    storageBucket: 'spotify-music-api-player.appspot.com',
    iosBundleId: 'com.example.musicplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQe_QKcL2mBHxyGLkgHN7m62oCRY8rt6o',
    appId: '1:339419575615:ios:657d0e31727b40c08f8f8a',
    messagingSenderId: '339419575615',
    projectId: 'spotify-music-api-player',
    storageBucket: 'spotify-music-api-player.appspot.com',
    iosBundleId: 'com.example.musicplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC5KopJ0p2AL_dG8H5ZbZn2y2Lz_I0V_0',
    appId: '1:339419575615:web:ae05ab5f88f048a08f8f8a',
    messagingSenderId: '339419575615',
    projectId: 'spotify-music-api-player',
    authDomain: 'spotify-music-api-player.firebaseapp.com',
    storageBucket: 'spotify-music-api-player.appspot.com',
    measurementId: 'G-C35GMHN8RM',
  );
}
